### PR TITLE
Style navbar, header, and footer to look consistent with main site

### PR DESCRIPTION
**Pull request by thecodingwizard**
Added some basic styling so that the blog site looks more like the main website. All the details are in this commit message: https://github.com/valkyrierobotics/valkyrierobotics.github.io/commit/42a9732d6f09095d213c8ab2f52db3f5930628f3

```
Changed navbar style to look consistent with main site.
    - The old code is commented out but not removed.
    - navigation.html is no longer included. All links are hardcoded.
      Should fix. Current links are "home" and "website".

Changed header style to look consistent with main site.
    - Increased height to 700px
    - Updated fonts
    - The background image is 2.4 MB!

Changed footer style to look consistent.
    - Changed background to black
    - Added github, email, and facebook icons
    - Note: There is an empty navigation element in the footer. It was
      not touched, so therefore not styled.
    - Note: For the facebook icon, the URL contains ?fref=ts. Looks like
      a referral parameter - we should probably remove it.

Also changed the font to Open Sans.
```

### CODE REVIEW

**Comment by m3rcuriel** [comment]
Do you want to maybe make the navbar just identical so it _seems_ like one site?

**Comment by thecodingwizard** [comment]
Alright - the navbars are identical now. Any other changes that I should make?

**Comment by m3rcuriel** [comment]
Change _config.yml back...

**Comment by thecodingwizard** [comment]
ah oops

**Comment by m3rcuriel** [comment]
Merged in 5c17e1d42cfabdf94416c6e80f77d4f8b066f545.

**Pull request closed without merging**
